# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TtroPopMenuSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TtroPopMenuSample

  pod 'PayWandBasicElements', :path => '../../PayWandBasicElements'
  # pod 'TtroPopMenu', :path => '../../TtroPopMenu'

  target 'TtroPopMenuSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TtroPopMenuSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
